server:
  port: 9003    # 指定端口

spring:
  application:
    name: tensquare-qa   # 模块名
  datasource:   # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.32.207:3307/tensquare_qa?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:      # 配置jpa
    database: mysql
    show-sql: true